image: denoland/deno:1.19.1

stages:
  - prepare
  - file-storage
  - blockchain

before_script:
  - shopt -s expand_aliases
  - alias drake='deno run --import-map ./import_map.json -A Drakefile.ts'
  - type drake

prepare-stg:
  stage: prepare
  when: manual
  environment: staging
  needs: []
  script:
    - drake write-file-ids

ipfs-stg:
  stage: file-storage
  when: manual
  environment: staging
  timeout: 3 hours 30 minutes
  needs: []
  script:
    - drake write-ipfs